version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    command: /bin/bash ./entrypoint.sh
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@passworD12"
      ACCEPT_EULA: "Y"
    volumes: 
        - ./db/data:/var/opt/mssql/data
        - ./db/docker-entrypoint.sh:/entrypoint.sh
        - ./db/docker-db-init.sh:/db-init.sh
        - ./db/mssql-init.sql:/db-init.sql

    